### ISSUE TITLE
Many texts are not translatable

### ISSUE THREAD

**Issue by boboldehampsink** [page-8/craft-manytomany#2]
Hi,

I want to translate this plugin to dutch, but many of the text strings you're using are not going through the translate filter. For example: "Add an entry" is always in english. Can this be fixed?

**Comment by page-8** [comment]
Hi Bob,

Yeah, this plugin was created for one of our specific needs and I thought I might as well let other people use it if they find it beneficial. That's why it doesn't support locales at this time either.

If you want to make a pull request or give me a list of areas you would like to go through the translate filter I can definitely accommodate that.

Thanks!

**Comment by boboldehampsink** [comment]
I'd say all ;-) but Add an entry is the most seen by the end-user, so i'd like that the most ofcourse.

**Comment by page-8** [comment]
Added as of 1.1.2
